version: "3.9"

services:
  database:
    image: 'bitnami/mysql:latest'
    environment:
      - MYSQL_ROOT_USER=ana
      - MYSQL_ROOT_PASSWORD=gabriela
      - MYSQL_DATABASE=functional
    ports:
      - 3306:3306
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: ["watchmedo", "auto-restart", "-d", "/app", "-p", "'*.py'", "--", "python3", "src/index.py"]
    depends_on:
      - "database"
    links:
      - "database"