version: "3.9"

services:
  database:
    image: 'bitnami/mysql:latest'
    environment:
      - MYSQL_ROOT_USER=ana
      - MYSQL_ROOT_PASSWORD=gabriela
      - MYSQL_DATABASE=functional
    ports:
      - 3306:3306
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      #RODAR COMANDO ABAIXO PARA CRIAR O VOLUME QUE FICA ATUALIZANDO (IDEAL PARA Q1,Q3,Q4, PRECISA ALTERAR O INDEX)
    # command: ["watchmedo", "auto-restart", "-d", "/app", "-p", "'*.py'", "--", "python3", "src/index.py", flask", "run", "--host=0.0.0.0"]
    command: ["flask", "run", "--host=0.0.0.0", "--reload"]
    #RODAR COMANDO ABAIXO PARA CRIAR O VOLUME APENAS UMA VEZ (IDEAL PARA Q2, PRECISA ALTERAR O INDEX)
    # command: ["python3", "src/index.py"]
    environment:
      - FLASK_APP=src/q5_AnaBezerra.py
      - FLASK_RUN_PORT=5001
    ports:
      - 5001:5001
    depends_on:
      - "database"
    links:
      - "database"